---
title: "Maps"
author: "Julia Englebert"
date: "4/22/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

options(scipen = 999)

library(haven)
library(tidyverse)
library(gt)
library(devtools)
library(tibble)
library(foreign)
library(scales)

# packages for mapping
library(leaflet)
library(spdplyr)
library(rmapshaper)
library(sf)
```

```{r testModel}
#
# model1 <- lm(data = mwdata, perc_school ~ state + land_in_farms)
```

# DATA WRANGLING

```{r allData}
# 1800s data

# Will comment on 1870s data, then repeat the process for all subsequent years
# Note that the codenames ARE DIFFERENT FOR EACH YEAR
# Even if the variable was measured in the same way
# See original codebook for details


# Read in all 1870 csv files
# Originally, R was returning this message:
# Column `STATE` joining factors with different levels, coercing to character vectorColumn `COUNTY` joining
# factors with different levels, coercing to character vector
# I got rid of it by converting all factors to characters

data1870a <- as_tibble(read.csv("raw-data/nhgis0002_csv/nhgis0002_ds16_1870_county.csv")) %>%
  mutate(GISJOIN = as.character(GISJOIN), STATE = as.character(STATE), COUNTY = as.character(COUNTY), 
         AREANAME = as.character(AREANAME))

data1870b <- as_tibble(read.csv("raw-data/nhgis0002_csv/nhgis0002_ds17_1870_county.csv")) %>%
  mutate(GISJOIN = as.character(GISJOIN), STATE = as.character(STATE), COUNTY = as.character(COUNTY), 
         AREANAME = as.character(AREANAME))

# Join the two datasets by STATEA and COUNTYA, which are the state and county codes

data1870j <- full_join(data1870a, data1870b, by = c("STATEA", "COUNTYA")) %>%
  
  # Mutate to get rid of the .x suffix on variables
  
  mutate(GISJOIN = GISJOIN.x, YEAR = YEAR.x, STATE = STATE.x, COUNTY = COUNTY.x) %>%
  
  # Mutate to rename varialbes of interest to uniform, comprehensible names
  # Some existing varialbes are combined to create the desired variables
  # See codebook
  
  mutate(value_farm = AJV001, n_farm = AJS001, cows =  AJ0003+AJ0005, horses = AJ0001, 
         avg_size = (AJT001*2 + AJT002*6 + AJT003*15 + AJT004*35 + AJT005*75 + AJT006*300 + AJT007*750 + 
                       AJT008*1200)/AKP001, value_implements = AKL001, pop = AJ3001, male = AKD001, 
         female = AKD002, enrolled = ALG001, urban_pop = AKE001, pct_urban = AKE001/AJ3001*100, 
         illiterate = AJ7001, acres_farms = AJU001+ AJU002+AJU003, 
         
         # Even though irrigation data doesn't exist for this year, I'm filling the columns in with NA
         # Later years will have irrigation data
         
         acres_irrigated = NA, pct_irrigated = NA) %>%
  
  # Mutate again to make new variables out of the ones you just created in the last mutate
  
  mutate(cows_per_person = cows/n_farm, pct_enrolled = enrolled/pop, pct_illiterate = illiterate/pop) %>%
  
  # Select the desired variables
  
  select(STATEA, COUNTYA, GISJOIN, YEAR, STATE, COUNTY, value_farm, value_implements, avg_size, n_farm,
         acres_farms, acres_irrigated, pct_irrigated, cows, cows_per_person, horses, pop, male, female,
         enrolled, pct_enrolled, urban_pop, pct_urban, illiterate, pct_illiterate)

# Now the dataset is much more manageable!

# Start on the next year, 1880, repeating the exact same process
# Lots of NA values due to scant data this year

data1880a <- as_tibble(read.csv("raw-data/nhgis0002_csv/nhgis0002_ds22_1880_county.csv")) %>%
  mutate(GISJOIN = as.character(GISJOIN), STATE = as.character(STATE), COUNTY = as.character(COUNTY), 
         AREANAME = as.character(AREANAME))

data1880b <- as_tibble(read.csv("raw-data/nhgis0002_csv/nhgis0002_ds23_1880_county.csv")) %>%
  mutate(GISJOIN = as.character(GISJOIN), STATE = as.character(STATE), COUNTY = as.character(COUNTY), 
         AREANAME = as.character(AREANAME))

data1880j <- full_join(data1880a, data1880b, by = c("STATEA", "COUNTYA")) %>%
  mutate(GISJOIN = GISJOIN.x, YEAR = YEAR.x, STATE = STATE.x, COUNTY = COUNTY.x) %>%
  mutate(value_farm = APN001+APO001+APQ001, n_farm = AOQ001, cows =  AOG004+AOG005, horses = AOG001, 
         avg_size = APG001, value_implements = APO001, pop = AOT001, male = AP1001, female = AP1002, 
         enrolled = NA, urban_pop = AO4001, pct_urban = AO4001/AOT001*100, illiterate = NA, 
         acres_farms = AOR001, acres_irrigated = NA, pct_irrigated = NA) %>%
  mutate(cows_per_person = cows/n_farm, pct_enrolled = enrolled/pop, pct_illiterate = illiterate/pop) %>%
  select(STATEA, COUNTYA, GISJOIN, YEAR, STATE, COUNTY, value_farm, value_implements, avg_size, n_farm, 
         acres_farms, acres_irrigated, pct_irrigated, cows, cows_per_person, horses, pop, male, female, 
         enrolled, pct_enrolled, urban_pop, pct_urban, illiterate, pct_illiterate)

# Start on 1890 data

data1890a <- as_tibble(read.csv("raw-data/nhgis0002_csv/nhgis0002_ds26_1890_county.csv")) %>%
  mutate(GISJOIN = as.character(GISJOIN), STATE = as.character(STATE), COUNTY = as.character(COUNTY), 
         AREANAME = as.character(AREANAME))

data1890b <- as_tibble(read.csv("raw-data/nhgis0002_csv/nhgis0002_ds27_1890_county.csv")) %>%
  mutate(GISJOIN = as.character(GISJOIN), STATE = as.character(STATE), COUNTY = as.character(COUNTY), 
         AREANAME = as.character(AREANAME))

data1890j <- full_join(data1890a, data1890b, by = c("STATEA", "COUNTYA")) %>%
  mutate(GISJOIN = GISJOIN.x, YEAR = YEAR.x, STATE = STATE.x, COUNTY = COUNTY.x) %>%
  mutate(value_farm = AUK001+AUK002+AUK003, n_farm = AS9001, cows = ASY002, horses = ASY003, 
         avg_size = ATW001, value_implements = AUK002, pop = AUM001, male = AV0001+AV0003+AV0005+AV0007, 
         female = AV0002+AV0004+AV0006+AV0008, enrolled = AVK005+AVK006+AVK007+AVK008, urban_pop = AUU001, 
         pct_urban = AUU001/AUM001*100, illiterate = NA, acres_farms = AUJ001+AUJ002, 
         acres_irrigated = AT2001, pct_irrigated = AT2001/(AUJ001+AUJ002)*100) %>%
  mutate(cows_per_person = cows/n_farm, pct_enrolled = enrolled/pop, pct_illiterate = illiterate/pop) %>%
  select(STATEA, COUNTYA, GISJOIN, YEAR, STATE, COUNTY, value_farm, value_implements, avg_size, n_farm, 
         acres_farms, acres_irrigated, pct_irrigated, cows, cows_per_person, horses, pop, male, female, 
         enrolled, pct_enrolled, urban_pop, pct_urban, illiterate, pct_illiterate)

# Before I mutated all of the data, running this code showed that all .x values are the same 
# as all .y values, so it was safe to eliminate the double columns as long as "problems" returned 0
# And it did!
  
#problems <- bind_rows(data1870j, data1880j, data1890j) %>% 
  #select(STATEA, COUNTYA, GISJOIN.x, GISJOIN.y, YEAR.x, YEAR.y, STATE.x, STATE.y, 
         #COUNTY.x, COUNTY.y, AREANAME.x, AREANAME.y) %>%
  #mutate(same = ifelse(GISJOIN.x == GISJOIN.y & YEAR.x == YEAR.y & STATE.x == STATE.y & 
                         #COUNTY.x == COUNTY.y & AREANAME.x == AREANAME.y, TRUE, FALSE)) %>%
  #filter(same == "FALSE") %>%
  #nrow()



# Read in the 1900s data

# Only do decennial census data
# Intermittent years only have AF12001: estimated population

# 1900

data1900a <- as_tibble(read.csv("raw-data/nhgis0003_csv/nhgis0003_ds30_1900_county.csv")) %>%
  mutate(GISJOIN = as.character(GISJOIN), STATE = as.character(STATE), COUNTY = as.character(COUNTY), 
         AREANAME = as.character(AREANAME))

data1900b <- as_tibble(read.csv("raw-data/nhgis0003_csv/nhgis0003_ds31_1900_county.csv")) %>%
  mutate(GISJOIN = as.character(GISJOIN), STATE = as.character(STATE), COUNTY = as.character(COUNTY), 
         AREANAME = as.character(AREANAME))

data1900j <- full_join(data1900a, data1900b, by = c("STATEA", "COUNTYA")) %>%
  mutate(GISJOIN = GISJOIN.x, YEAR = YEAR.x, STATE = STATE.x, COUNTY = COUNTY.x) %>%
  mutate(value_farm = AWV001, n_farm = AW3001, cows = AW7001, horses = AW7002, 
         avg_size = AXE001, value_implements = AWW003, pop = AWS001, male = AZ0001,female = AZ0001, 
         enrolled = NA, urban_pop = NA, pct_urban = NA, illiterate = AYS001+AYS002+AYS003+AYS004+AYS005, 
         acres_farms = AWT001, acres_irrigated = AX8001, pct_irrigated = AX8001/AWT001*100) %>%
  mutate(cows_per_person = cows/n_farm, pct_enrolled = enrolled/pop, pct_illiterate = illiterate/pop) %>%
  select(STATEA, COUNTYA, GISJOIN, YEAR, STATE, COUNTY, value_farm, value_implements, avg_size, n_farm, 
         acres_farms, acres_irrigated, pct_irrigated, cows, cows_per_person, horses, pop, male, female, 
         enrolled, pct_enrolled, urban_pop, pct_urban, illiterate, pct_illiterate)

# 1910

data1910a <- as_tibble(read.csv("raw-data/nhgis0003_csv/nhgis0003_ds36_1910_county.csv")) %>%
  mutate(GISJOIN = as.character(GISJOIN), STATE = as.character(STATE), COUNTY = as.character(COUNTY), 
         AREANAME = as.character(AREANAME))

data1910b <- as_tibble(read.csv("raw-data/nhgis0003_csv/nhgis0003_ds37_1910_county.csv")) %>%
  mutate(GISJOIN = as.character(GISJOIN), STATE = as.character(STATE), COUNTY = as.character(COUNTY), 
         AREANAME = as.character(AREANAME))

data1910j <- full_join(data1910a, data1910b, by = c("STATEA", "COUNTYA")) %>%
  mutate(GISJOIN = GISJOIN.x, YEAR = YEAR.x, STATE = STATE.x, COUNTY = COUNTY.x) %>%
  mutate(value_farm = A0F001, n_farm = A1H001, cows = A1F001+A1F002, horses = NA, 
         avg_size = A21001/A1H001, value_implements = A0Q005, pop = A0E001, male = NA, female = NA, 
         enrolled = A4F001, urban_pop = A36001, pct_urban = A36001/A0E001*100, illiterate = A38001, 
         acres_farms = A21001, acres_irrigated = A0G001, pct_irrigated = A0G001/A21001*100) %>%
  mutate(cows_per_person = cows/n_farm, pct_enrolled = enrolled/pop, pct_illiterate = illiterate/pop) %>%
  select(STATEA, COUNTYA, GISJOIN, YEAR, STATE, COUNTY, value_farm, value_implements, avg_size, n_farm, 
         acres_farms, acres_irrigated, pct_irrigated, cows, cows_per_person, horses, pop, male, female, 
         enrolled, pct_enrolled, urban_pop, pct_urban, illiterate, pct_illiterate)

#1920
  
data1920a <- as_tibble(read.csv("raw-data/nhgis0003_csv/nhgis0003_ds43_1920_county.csv")) %>%
  mutate(GISJOIN = as.character(GISJOIN), STATE = as.character(STATE), COUNTY = as.character(COUNTY), 
         AREANAME =  as.character(AREANAME))

data1920b <- as_tibble(read.csv("raw-data/nhgis0003_csv/nhgis0003_ds224_1920_county.csv")) %>%
  mutate(GISJOIN = as.character(GISJOIN), STATE = as.character(STATE), COUNTY = as.character(COUNTY), 
         AREANAME = as.character(AREANAME))

data1920c <- as_tibble(read.csv("raw-data/nhgis0003_csv/nhgis0003_ds210_1920_county.csv")) %>%
  mutate(GISJOIN = as.character(GISJOIN), STATE = as.character(STATE), COUNTY = as.character(COUNTY), 
         AREANAME = as.character(AREANAME))

data1920j <- full_join(data1920a, data1920b, by = c("STATEA", "COUNTYA"))
data1920j <- full_join(data1920j, data1920c, by = c("STATEA", "COUNTYA"))
data1920j <- data1920j %>%
  mutate(GISJOIN = GISJOIN.x, YEAR = YEAR.x, STATE = STATE.x, COUNTY = COUNTY.x) %>%
  mutate(value_farm = A8P001+A8P002+A8P003+A8P004, n_farm = AB3P001, cows = NA, horses = NA, 
         avg_size = AB3T001/AB3P001, value_implements = A8P003, pop = A81001, male = A8B001, 
         female = A8B002, enrolled = A7N001+A7N002+A7N003+A7N004, urban_pop = A80001, 
         pct_urban = A80001/A81001*100, illiterate = A7U001, acres_farms = AB3T001, 
         acres_irrigated = AB6L001, pct_irrigated = AB6L002/AB3T001*100) %>%
  mutate(cows_per_person = cows/n_farm, pct_enrolled = enrolled/pop, pct_illiterate = illiterate/pop) %>%
  select(STATEA, COUNTYA, GISJOIN, YEAR, STATE, COUNTY, value_farm, value_implements, avg_size, n_farm, 
         acres_farms, acres_irrigated, pct_irrigated, cows, cows_per_person, horses, pop, male, female, 
         enrolled, pct_enrolled, urban_pop, pct_urban, illiterate, pct_illiterate)

#1930
# 1930 has more datasets available than previous years

data1930a <- as_tibble(read.csv("raw-data/nhgis0003_csv/nhgis0003_ds212_1930_county.csv")) %>%
  mutate(GISJOIN = as.character(GISJOIN), STATE = as.character(STATE), COUNTY = as.character(COUNTY), 
         AREANAME = as.character(AREANAME))

data1930b <- as_tibble(read.csv("raw-data/nhgis0003_csv/nhgis0003_ds224_1930_county.csv")) %>%
  mutate(GISJOIN = as.character(GISJOIN), STATE = as.character(STATE), COUNTY = as.character(COUNTY), 
         AREANAME = as.character(AREANAME))

data1930c <- as_tibble(read.csv("raw-data/nhgis0003_csv/nhgis0003_ds52_1930_county.csv")) %>%
  mutate(GISJOIN = as.character(GISJOIN), STATE = as.character(STATE), COUNTY = as.character(COUNTY), 
         AREANAME = as.character(AREANAME))

data1930d <- as_tibble(read.csv("raw-data/nhgis0003_csv/nhgis0003_ds53_1930_county.csv")) %>%
  mutate(GISJOIN = as.character(GISJOIN), STATE = as.character(STATE), COUNTY = as.character(COUNTY), 
         AREANAME = as.character(AREANAME))

data1930e <- as_tibble(read.csv("raw-data/nhgis0003_csv/nhgis0003_ds54_1930_county.csv")) %>%
  mutate(GISJOIN = as.character(GISJOIN), STATE = as.character(STATE), COUNTY = as.character(COUNTY), 
         AREANAME = as.character(AREANAME))

data1930f <- as_tibble(read.csv("raw-data/nhgis0003_csv/nhgis0003_ds55_1930_county.csv")) %>%
  mutate(GISJOIN = as.character(GISJOIN), STATE = as.character(STATE), COUNTY = as.character(COUNTY), 
         AREANAME = as.character(AREANAME))

data1930j <- full_join(data1930a, data1930b, by = c("STATEA", "COUNTYA"))
data1930j <- full_join(data1930j, data1930c, by = c("STATEA", "COUNTYA"))
data1930j <- full_join(data1930j, data1930d, by = c("STATEA", "COUNTYA"))
data1930j <- full_join(data1930j, data1930e, by = c("STATEA", "COUNTYA"))
data1930j <- full_join(data1930j, data1930f, by = c("STATEA", "COUNTYA"))

data1930j <- data1930j %>%
  mutate(GISJOIN = GISJOIN.x, YEAR = YEAR.x, STATE = STATE.x, COUNTY = COUNTY.x) %>%
  mutate(value_farm = BFD001+BFD002+BFD004+ACEO001, n_farm = AB95001, cows = NA, horses = NA, 
         avg_size = ACAA001, value_implements = BFD004, pop = BCX001, male = BC3001, 
         female = BC3002, enrolled = BDT001+BDT002+BDT003+BDT004, urban_pop = BDX001, 
         pct_urban = BDX001/BDP001*100, illiterate = BDV001, acres_farms = AB98001, 
         acres_irrigated = ACEX002, pct_irrigated = ACEX002/AB98001*100) %>%
  mutate(cows_per_person = cows/n_farm, pct_enrolled = enrolled/pop, pct_illiterate = illiterate/pop) %>%
  select(STATEA, COUNTYA, GISJOIN, YEAR, STATE, COUNTY, value_farm, value_implements, avg_size, n_farm, 
         acres_farms, acres_irrigated, pct_irrigated, cows, cows_per_person, horses, pop, male, female, 
         enrolled, pct_enrolled, urban_pop, pct_urban, illiterate, pct_illiterate)

# 1940

data1940a <- as_tibble(read.csv("raw-data/nhgis0003_csv/nhgis0003_ds224_1940_county.csv")) %>%
  mutate(GISJOIN = as.character(GISJOIN), STATE = as.character(STATE), COUNTY = as.character(COUNTY), 
         AREANAME = as.character(AREANAME))

data1940b <- as_tibble(read.csv("raw-data/nhgis0003_csv/nhgis0003_ds77_1940_county.csv")) %>%
  mutate(GISJOIN = as.character(GISJOIN), STATE = as.character(STATE), COUNTY = as.character(COUNTY), 
         AREANAME = as.character(AREANAME))

data1940c <- as_tibble(read.csv("raw-data/nhgis0003_csv/nhgis0003_ds78_1940_county.csv")) %>%
  mutate(GISJOIN = as.character(GISJOIN), STATE = as.character(STATE), COUNTY = as.character(COUNTY), 
         AREANAME = as.character(AREANAME))

data1940j <- full_join(data1940a, data1940b, by = c("STATEA", "COUNTYA"))
data1940j <- full_join(data1940j, data1940c, by = c("STATEA", "COUNTYA"))
data1940j <- data1940j %>%
  mutate(GISJOIN = GISJOIN.x, YEAR = YEAR.x, STATE = STATE.x, COUNTY = COUNTY.x) %>%
  
  # value_farm is missing the land & livestock components!!
  # this variable only includings buildings and implements
  
  mutate(value_farm = BWD001+BWD002, n_farm = BY1001, cows = NA, horses = NA, 
         avg_size = BY0001, value_implements = BWD002, pop = BVU001, male = BVY001, 
         female = BVY002, enrolled = BWU001+BWU002+BWU003+BWU004+BWU005, urban_pop = NA, 
         pct_urban = NA, illiterate = NA, acres_farms = BY3001, 
         acres_irrigated = NA, pct_irrigated = NA) %>%
  mutate(cows_per_person = cows/n_farm, pct_enrolled = enrolled/pop, 
         pct_illiterate = illiterate/pop) %>%
  select(STATEA, COUNTYA, GISJOIN, YEAR, STATE, COUNTY, value_farm, value_implements, avg_size, n_farm, 
         acres_farms, acres_irrigated, pct_irrigated, cows, cows_per_person, horses, pop, male, female, 
         enrolled, pct_enrolled, urban_pop, pct_urban, illiterate, pct_illiterate)

# 1950

data1950a <- as_tibble(read.csv("raw-data/nhgis0003_csv/nhgis0003_ds83_1950_county.csv")) %>%
  mutate(GISJOIN = as.character(GISJOIN), STATE = as.character(STATE), COUNTY = as.character(COUNTY), 
         AREANAME =  as.character(AREANAME))

data1950b <- as_tibble(read.csv("raw-data/nhgis0003_csv/nhgis0003_ds84_1950_county.csv")) %>%
  mutate(GISJOIN = as.character(GISJOIN), STATE = as.character(STATE), COUNTY = as.character(COUNTY), 
         AREANAME = as.character(AREANAME))

data1950j <- full_join(data1950a, data1950b, by = c("STATEA", "COUNTYA")) %>%
  mutate(GISJOIN = GISJOIN.x, YEAR = YEAR.x, STATE = STATE.x, COUNTY = COUNTY.x, 
         B18001 = as.numeric(B18001)) %>%
  
  # value_farm is missing the implements & livestock components!!
  # This variable only includings buildings and land
  
  mutate(value_farm = B3M001, n_farm = B3Z001, cows = NA, horses = NA, 
         avg_size = B3L001, value_implements = NA, pop = B18001, male = B3E001, 
         female = B3E002, enrolled = B2A001+B2A002+B2A003+B2A004+B2A005, urban_pop = B2J001, 
         pct_urban = B2J001/B18001*101, illiterate = NA, acres_farms = B3K001, 
         acres_irrigated = NA, pct_irrigated = NA) %>%
  mutate(cows_per_person = cows/n_farm, pct_enrolled = enrolled/pop, pct_illiterate = illiterate/pop) %>%
  select(STATEA, COUNTYA, GISJOIN, YEAR, STATE, COUNTY, value_farm, value_implements, avg_size, n_farm, 
         acres_farms, acres_irrigated, pct_irrigated, cows, cows_per_person, horses, pop, male, female, 
         enrolled, pct_enrolled, urban_pop, pct_urban, illiterate, pct_illiterate)

#1960
# The data are SPARSE yikes

data1960a <- as_tibble(read.csv("raw-data/nhgis0003_csv/nhgis0003_ds89_1960_county.csv")) %>%
  mutate(GISJOIN = as.character(GISJOIN), STATE = as.character(STATE), COUNTY = as.character(COUNTY), 
         AREANAME =  as.character(AREANAME))

data1960b <- as_tibble(read.csv("raw-data/nhgis0003_csv/nhgis0003_ds90_1960_county.csv")) %>%
  mutate(GISJOIN = as.character(GISJOIN), STATE = as.character(STATE), COUNTY = as.character(COUNTY), 
         AREANAME = as.character(AREANAME))

data1960c <- as_tibble(read.csv("raw-data/nhgis0003_csv/nhgis0003_ds91_1960_county.csv")) %>%
  mutate(GISJOIN = as.character(GISJOIN), STATE = as.character(STATE), COUNTY = as.character(COUNTY), 
         AREANAME = as.character(AREANAME))

data1960j <- full_join(data1960a, data1960b, by = c("STATEA", "COUNTYA"))
data1960j <- full_join(data1960j, data1960c, by = c("STATEA", "COUNTYA"))
data1960j <- data1960j %>%
  mutate(value_farm = NA, n_farm = NA, cows = NA, horses = NA, 
         avg_size = NA, value_implements = NA, pop = B47001, male = B5H001, 
         female = B5H002, enrolled = NA, urban_pop = NA, pct_urban = NA, illiterate = NA, 
         acres_farms = NA, acres_irrigated = NA, pct_irrigated = NA) %>%
  mutate(cows_per_person = cows/n_farm, pct_enrolled = enrolled/pop, pct_illiterate = illiterate/pop) %>%
  select(STATEA, COUNTYA, GISJOIN, YEAR, STATE, COUNTY, value_farm, value_implements, avg_size, n_farm, 
         acres_farms, acres_irrigated, pct_irrigated, cows, cows_per_person, horses, pop, male, female, 
         enrolled, pct_enrolled, urban_pop, pct_urban, illiterate, pct_illiterate)

```

## Join the cleaned sets

```{r boundData}
# Running this code (before I renamed variables) showed that all .x values are the same as all .y values, 
# so it was safe to eliminate the double columns
# as long as problems returned 0 (and it did!)
# this didn't check for .x.x or .y.x. columns, etc.
  
#problems <- bind_rows(data1900j, data1910j, data1920j, data1930j, data1940j, data1950j, data1960j) %>% 
  #select(STATEA, COUNTYA, GISJOIN.x, GISJOIN.y, YEAR.x, YEAR.y, STATE.x, STATE.y, 
         #COUNTY.x, COUNTY.y) %>%
  #mutate(same = ifelse(GISJOIN.x == GISJOIN.y & YEAR.x == YEAR.y & STATE.x == STATE.y & 
                         #COUNTY.x == COUNTY.y, TRUE, FALSE)) %>%
  #filter(same == "FALSE") %>%
  #nrow()

  
# Now bind all of the years together!
# Add pct_male and avg_value_farm variables
# Filter for only midwestern states/territories

allData <- as_tibble(bind_rows(data1870j, data1880j, data1890j, 
                       data1900j, data1910j, data1920j, data1930j, data1940j, data1950j, data1960j)) %>%
  mutate(pct_male = male/pop, avg_value_farm = value_farm/n_farm, cows_per_farm = cows_per_person, 
         avg_value_implements = value_implements/n_farm) %>%
  
  # I mislabeled cows_per_farm as cows_per_person, so I'm doing damage control now
  
  select(!cows_per_person) %>%
  filter(STATE == "North Dakota" | STATE == "South Dakota" | STATE == "Dakota Territory" | 
           STATE == "Nebraska" | STATE == "Minnesota" | STATE == "Iowa" | STATE == "Missouri" | 
           STATE == "Wisconsin" | STATE == "Illinois" | STATE == "Kansas" | STATE == "Michigan" | 
           STATE == "Indiana" | STATE == "Ohio")

# This will be used for mapping!
# All relevant columns must be numeric in order to function properly
# Renaming them also helps make the maps more easily interpretable
# But it's not ideal for working with the data in other contexts, hence the separate set

mwData <- allData %>%
  mutate("Value of Farms" = as.numeric(value_farm), "Average Farm Value" = as.numeric(avg_value_farm), 
         "Value of Implements" = as.numeric(value_implements), 
         "Average Implement Value" = as.numeric(avg_value_implements), 
         "Average Farm Size" = as.numeric(avg_size), "Number of Farms" = as.numeric(n_farm), 
         "Acres of Farmland" = as.numeric(acres_farms), "Irrigated Acres" = as.numeric(acres_irrigated), 
         "Percentage of Farmland Irrigated" = as.numeric(pct_irrigated), "Number of Cows" = as.numeric(cows),
         "Number of Cows per Farm" = as.numeric(cows_per_farm), "Number of Horses" = as.numeric(horses), 
         "Total Population" = as.numeric(pop), "Male Population" = as.numeric(male), 
         "Female Population" = as.numeric(female), "Male Percentage of Population" = as.numeric(pct_male),
         "Total School Enrollment" = as.numeric(enrolled), 
         "Percentage School Enrollment" = as.numeric(pct_enrolled), 
         "Urban Population" = as.numeric(urban_pop), 
         "Percent of Population in Urban Areas" = as.numeric(pct_urban), 
         "Illiterate Population" = as.numeric(illiterate), 
         "Illiteracy Rate" = as.numeric(pct_illiterate)) %>%
  select(STATEA, COUNTYA, GISJOIN, YEAR, STATE, COUNTY, 
         "Value of Farms", "Average Farm Value", "Value of Implements", "Average Implement Value",
                   "Average Farm Size", "Number of Farms", "Acres of Farmland", "Irrigated Acres", 
                   "Percentage of Farmland Irrigated", "Number of Cows", "Number of Cows per Farm", 
                   "Number of Horses", "Total Population", "Male Population", "Female Population", 
                   "Male Percentage of Population", "Total School Enrollment", 
                   "Percentage School Enrollment", "Urban Population", 
                   "Percent of Population in Urban Areas", "Illiterate Population", "Illiteracy Rate")

# saving this for later
# will need in shiny app
#sliderOptions <- c("Value of Farms", "Average Farm Value", "Value of Implements", "Average Implement Value",
                   #"Average Farm Size", "Number of Farms", "Acres of Farmland", "Irrigated Acres", 
                   #"Percentage of Farmland Irrigated", "Number of Cows", "Number of Cows per Farm", 
                   #"Number of Horses", "Total Population", "Male Population", "Female Population", 
                   #"Male Percentage of Population", "Total School Enrollment", 
                   #"Percentage School Enrollment", "Urban Population", 
                   #"Percent of Population in Urban Areas", "Illiterate Population", "Illiteracy Rate")

  
```

# Shiny 
## Preparation

```{r shapefiles}

# Now save the gis data with short names for sake of the shiny app
# hopefully this will work...

dsn1870 <- "raw-data/nhgis0002_shape/nhgis0002_shapefile_tl2008_us_county_1870"
  layer1870 <- "US_county_1870_conflated"
dsn1880 <- "raw-data/nhgis0002_shape/nhgis0002_shapefile_tl2008_us_county_1880"
  layer1880 <- "US_county_1880_conflated"
dsn1890 <- "raw-data/nhgis0002_shape/nhgis0002_shapefile_tl2008_us_county_1890"
  layer1890 <- "US_county_1890_conflated"
dsn1900 <- "raw-data/nhgis0003_shape/nhgis0003_shapefile_tl2008_us_county_1900"
  layer1900 <- "US_county_1900_conflated"
dsn1910 <- "raw-data/nhgis0003_shape/nhgis0003_shapefile_tl2008_us_county_1910"
  layer1910 <- "US_county_1910_conflated"
dsn1920 <- "raw-data/nhgis0003_shape/nhgis0003_shapefile_tl2008_us_county_1920"
  layer1920 <- "US_county_1920_conflated"
dsn1930 <- "raw-data/nhgis0003_shape/nhgis0003_shapefile_tl2008_us_county_1930"
  layer1930 <- "US_county_1930_conflated"
dsn1940 <- "raw-data/nhgis0003_shape/nhgis0003_shapefile_tl2008_us_county_1940"
  layer1940 <- "US_county_1940_conflated"
dsn1950 <- "raw-data/nhgis0003_shape/nhgis0003_shapefile_tl2008_us_county_1950"
  layer1950 <- "US_county_1950_conflated"
dsn1960 <- "raw-data/nhgis0003_shape/nhgis0003_shapefile_tl2008_us_county_1960"
  layer1960 <- "US_county_1960_conflated"

# Make a tibble of all the shapefiles that you'll need
  shapefiles <- tibble(Year = c(1870, 1880, 1890, 1900, 1910, 1920, 1930, 1940, 1950, 1960), 
                     Dsn = c(dsn1870, dsn1880, dsn1890, dsn1900, dsn1910, dsn1920, dsn1930, 
                             dsn1940, dsn1950, dsn1960),
                     Layer = c(layer1870, layer1880, layer1890, layer1900, layer1910, layer1920, 
                     layer1930, layer1940, layer1950, layer1960))
```

## Output

```{r genericGis}

# df %>% filter(b == !!b)

# gis template for any year/variable desired
# only change these two lines!
year <- 1870
myvar <- "Average Farm Value"

datayear <- mwData %>%
  # use get() to use the stored variable
  # idk why, but it doesn't work without this
  # the variable must be converted to a double in the original mwData dataset
  mutate(myvariable = (get(myvar))) %>%
  filter(YEAR == year, myvariable > 0) %>%
  select(GISJOIN, myvariable)

# Import Census Tract Shapefile into R as SpatialPolygonsDataFrameFormat (SP Dataframe)
# dsn is location of folder which contains shapefiles, (.proj, .shp etc.)
# layer is the filename of the .shp file inside the
# folder dsn points to. 

dsnyear <- shapefiles %>% 
  filter(Year == year) %>% 
  pull(Dsn)
layeryear <- shapefiles %>% 
  filter(Year == year) %>% 
  pull(Layer)

countyyear <- sf::st_read(dsn = dsnyear,
                         layer = layeryear)

countyyear <-
  countyyear %>%
  merge(datayear, "GISJOIN")


# Set projection of tracts dataset to `projection` required by leaflet

countyyear <- sf::st_transform(countyyear, crs="+init=epsg:4326")

# Condense size of data for faster processing

countyyear <- rmapshaper::ms_simplify(countyyear)

# Set palette color

pal <- colorNumeric("viridis", NULL)

#  Plot the data

# use shiny to add a title, which will be be equivalent to myvar

leaflet(countyyear) %>%
  addTiles() %>%
  addPolygons(stroke = FALSE, smoothFactor = 0.3, fillOpacity = 1,
              fillColor = ~pal(myvariable)) %>%
  addLegend(pal = pal, values = ~myvariable, opacity = 1.0, title = myvar)

```


```{r shiny, eval=FALSE}

# Pasting this here in case my computer explodes

# This is a Shiny web application. You can run the application by clicking
# the 'Run App' button above.
#
# Find out more about building applications with Shiny here:
#
#    http://shiny.rstudio.com/
#

library(shiny)
library(haven)
library(tidyverse)
library(gt)
library(devtools)
library(tibble)
library(foreign)
library(scales)
library(shinythemes)
library(plotly)
library(leaflet)
library(broom)

# packages for mapping
library(leaflet)
library(spdplyr)
library(rmapshaper)
library(sf)

# The real data

data1870a <- read.csv("raw-data/nhgis0002_csv/nhgis0002_ds16_1870_county.csv")
data1870b <- read.csv("raw-data/nhgis0002_csv/nhgis0002_ds17_1870_county.csv")
data1870j <- full_join(data1870a, data1870b, by = c("GISJOIN", "STATE", "COUNTY"))

data1880a <- read.csv("raw-data/nhgis0002_csv/nhgis0002_ds22_1880_county.csv") 
data1880b <- read.csv("raw-data/nhgis0002_csv/nhgis0002_ds23_1880_county.csv")
data1880j <- full_join(data1880a, data1880b, by = c("GISJOIN", "STATE", "COUNTY"))

data1890a <- read.csv("raw-data/nhgis0002_csv/nhgis0002_ds26_1890_county.csv")
data1890b <- read.csv("raw-data/nhgis0002_csv/nhgis0002_ds27_1890_county.csv")
data1890j <- full_join(data1890a, data1890b, by = c("GISJOIN", "STATE", "COUNTY"))

data1800s <- bind_rows(data1870j, data1880j, data1890j)


# I'm not actually using this data anymore
# I just wanted to make sure I could get my plots running smoothly
tbl_1 <- read_por("ICPSR_04254_ag/DS0001/04254-0001-Data.por", col_select = c(NAME, UNFIPS, FML_XX_A, ARE_XX_A, FRM_XX_Q, PRP_XX_V, IMP_XX_V, AFP_XX_V)) %>%
    rename(name = NAME, fips = UNFIPS, land_in_farms = FML_XX_A, total_area = ARE_XX_A, num_farms = FRM_XX_Q, value_farms = PRP_XX_V, value_implements = IMP_XX_V, value_production_betterments_stocks = AFP_XX_V)

tbl_3 <- read_por("ICPSR_04254_ag/DS0003/04254-0003-Data.por", col_select = c(NAME, UNFIPS, FML_XX_A, ARE_XX_A, FRM_XX_Q, PRP_XX_V, IMP_XX_V, AFP_XX_V))%>%
    rename(name = NAME, fips = UNFIPS, land_in_farms = FML_XX_A, total_area = ARE_XX_A, num_farms = FRM_XX_Q, value_farms = PRP_XX_V, value_implements = IMP_XX_V, value_production_betterments_stocks = AFP_XX_V)

tbl_5 <- read_por("ICPSR_04254_ag/DS0005/04254-0005-Data.por", col_select = c(NAME, UNFIPS, FML_XX_A, ARE_XX_A, FRM_XX_Q, PRP_OF_V, IMP_XX_V, CRO_XX_V)) %>%
    rename(name = NAME, fips = UNFIPS, land_in_farms = FML_XX_A, total_area = ARE_XX_A, num_farms = FRM_XX_Q, value_implements = IMP_XX_V, value_crops = CRO_XX_V) %>%
    mutate(value_farms = PRP_OF_V) %>%
    mutate(value_livestock = "NA", value_productsNotFed = "NA") %>%
    select(name, fips, land_in_farms, total_area, num_farms, value_farms, value_implements, value_livestock, value_productsNotFed)

tbl_1_d <- read_por("ICPSR_04296_demog/DS0001/04296-0001-Data.por", col_select = c(NAME, UNFIPS, TTOT, FT0_4, FT5_9, FT10_14, FT15_19, FT20_24, FT25_29, MT0_4, MT5_9, MT10_14, MT15_19, MT20_24, MT25_29, POP10P, SCH)) %>%
    rename(name = NAME, fips = UNFIPS, total = TTOT, people_over_10 = POP10P, pupils_in_school = SCH) %>%
    mutate(fem_5_24 = FT5_9 + FT10_14 + FT15_19 + FT20_24, mal_5_24 = MT5_9 + MT10_14 + MT15_19 + MT20_24)

tbl_3_d <- read_por("ICPSR_04296_demog/DS0003/04296-0003-Data.por", col_select = c(NAME, UNFIPS, TTOT, FT0_4, FT5_9, FT10_14, FT15_19, FT20_24, FT25_29, MT0_4, MT5_9, MT10_14, MT15_19, MT20_24, MT25_29, SCH)) %>%
    rename(name = NAME, fips = UNFIPS, total = TTOT, pupils_in_school = SCH) %>%
    mutate(fem_5_24 = FT5_9 + FT10_14 + FT15_19 + FT20_24, mal_5_24 = MT5_9 + MT10_14 + MT15_19 + MT20_24)

tbl_5_d <- read_por("ICPSR_04296_demog/DS0005/04296-0005-Data.por", col_select = c(NAME, UNFIPS, TTOT, FT0_4, FT5_9, FT10_14, FT15_19, FT20_24, FT25_29, MT0_4, MT5_9, MT10_14, MT15_19, MT20_24, MT25_29, SCH69, SCH1014, SCH1517, SCH1820)) %>% 
    rename(name = NAME, fips = UNFIPS, total = TTOT) %>%
    mutate(fem_5_24 = FT5_9 + FT10_14 + FT15_19 + FT20_24, mal_5_24 = MT5_9 + MT10_14 + MT15_19 + MT20_24,
           # Inconsistent age ranges
           # Not sure how to fix this
           pupils_in_school_6_20 = SCH69 + SCH1014 + SCH1517 + SCH1820)

j_1870 <- full_join(tbl_1, tbl_1_d, by = "fips") %>% 
    mutate(perc_school = pupils_in_school/(fem_5_24 + mal_5_24)*100) %>%
    select(name.x, fips, value_farms, perc_school) %>%
    group_by(fips)

j_1870 <- na.omit(j_1870)

j_1890 <- full_join(tbl_3, tbl_3_d, by = "fips") %>%
    mutate(perc_school = pupils_in_school/(fem_5_24 + mal_5_24)*100) %>%
    select(name.x, fips, value_farms, perc_school) %>%
    group_by(fips)

j_1890 <- na.omit(j_1890)


j_1910 <- full_join(tbl_5, tbl_5_d, by = "fips") %>%
    mutate(perc_school = pupils_in_school_6_20/(fem_5_24 + mal_5_24)*100) %>%
    select(name.x, fips, value_farms, perc_school) %>%
    group_by(fips)

j_1910 <- na.omit(j_1910)


b_1870_1910 <- bind_rows("1870" = j_1870, "1890" = j_1890, "1910" = j_1910, .id = "year") %>%
    group_by(year) 

# this should be done by state, not fips!!!
model1 <- lm(data = b_1870_1910, perc_school ~ fips + value_farms) %>% 
    tidy(conf.int = TRUE) %>% 
    gt() %>%
    fmt_number(data = ., columns = c("estimate", "std.error", "statistic", "p.value", "conf.low", "conf.high"), decimals = 2)

# Input

ui <- fluidPage(
    
    # flatly is a nice theme to make the tabs look put together
    
    # Application title
    
    navbarPage("Agriculture and Education in the U.S.", theme = shinytheme("flatly"),
               
               # remember that tab panel is for what shows up in the tab, and title panel is 
               # for what shows up at the top of the page within the tab                  
               
               tabPanel("Tab 1",
                        
                        # Give the page a title
                        titlePanel("Relationship Between Farm Value and Education, by County"),
                        
                        # Generate a row with a sidebar
                        sidebarLayout(      
                            
                            # Define the sidebar with one input
                            # insteaad of region, I want year ######
                            sidebarPanel(
                                selectInput("year", "Year:", 
                                            choices=c("1870" = "1870", "1890" = "1890", "1910" = "1910"), 
                                            multiple = TRUE)),
                            helpText("From Great Plains Population and Environment Survey Agricultural and Social & Demographic Data.")
                        ),
                        
                        # Create a spot for the plot
                        mainPanel(
                            tabsetPanel(id = "tabsMain",
                                        tabPanel("Plot",
                                                 
                                                 # this tells the UI what plot to put 
                                                 
                                                 plotOutput("agPlot")  
                                        )))),
               tabPanel("Models",
                        
                        # Give the page a title
                        titlePanel("Relationship Between Farm Value and Education, by County"),
                        p("Make some models! (See notes)"),
                        gt_output("model1")
               ),
               tabPanel("Maps",
                
                # Give the page a title
                titlePanel("Title Relating to Maps"),
                p("Add a slider for different years/variables & figure out how to get two maps side by side"),
                p("Maps may take up to 30 seconds to load."),
               leafletOutput("map1"),
               p()),
               
               tabPanel("About",
                        
                        # Give the page a title
                        titlePanel("About this project"),
                        p("My name is Julia Englebert. I am a senior at Harvard College studying Near Eastern Languages and Civilizations with a secondary field in Ethnicity, Migration, and Rights. Some of my academic interests include the history and future of Midwestern agriculture, and the role of data science in shaping social policy."),
                        br(),
                        p("This project uses historical census and American Community Survey (ACS) data to explore correlations between agriculture and education in the Midwestern United States. By joining the two datasets, the former containing agricultural data and the later containing demographic data, I was able to look at the impact of farming, land value, crop value, and more on education in Midwestern communities over the course of a century. 
                        I chose this particular time range in part because of the data that was available to me, and in part due to the economic, industrial, and education policy changes that ocurred from 1870 to 1960. 
                          My data is sourced from the IPUMS National Historical Geographic Information System (NHGIS) at nhgis.org. IPUMS provides census data from around the world, but my project focuses specifically on the United States from 1870 to 1960. All datasets and gis files used for this project can be downloaded from the NHGIS Data Finder:"),
                        p(a(href="https://data2.nhgis.org/main", "NHGIS Data Finder")),
                        br(),
                        p("To see more of my work, please visit my Github account:"),
                        p(a(href="https://github.com/julia-englebert", "Julia Englebert")),
                        br(),
                        titlePanel("Citations"),
                        p("Steven Manson, Jonathan Schroeder, David Van Riper, and Steven Ruggles. IPUMS National Historical Geographic Information System: Version 14.0 [Database]. Minneapolis, MN: IPUMS. 2019. http://doi.org/10.18128/D050.V14.0"),
                        p("The College of William and Mary and the Minnesota Population Center. School Attendance Boundary Information System (SABINS): Version 1.0. Minneapolis, MN: University of Minnesota 2011.")
               )
    ))



# use plotly to allow hover text to appear on plots, giving more info about the point

server <- function(input, output) {
    
    # Fill in the spot we created for a plot
    output$agPlot <- renderPlot({
        
        # Render a plot
        b_1870_1910 %>% 
            filter(year %in% input$year) %>% 
            group_by(year) %>%
            ggplot(aes(x = value_farms, y = perc_school, color = year)) + 
            geom_point(alpha = 0.5) + 
            ylim(0, 100) + 
            geom_smooth(method = "lm") + 
            labs(title = "Relationship Between Farm Value and Education, by County", 
                 subtitle = "Great Plains Region, United States", 
                 x = "Total Dollar Value of Farms", 
                 y = "Percent Students Ages 5-24 Enrolled in School") +
            scale_x_log10(labels = comma) +
            theme_classic()
    })
    
    output$map1 <- renderLeaflet({
            data1870 <- data1870j %>%
                filter(STATE == "North Dakota" | STATE == "South Dakota" | STATE == "Nebraska" | STATE == "Minnesota" | STATE == "Iowa" | STATE == "Missouri" | STATE == "Wisconsin" | STATE == "Illinois" | STATE == "Kansas" | STATE == "Michigan" | STATE == "Indiana" | STATE == "Ohio", AJX001 > 0) %>%
                mutate(valueAllFarmProds1870 = AJX001) %>%
                select(GISJOIN, valueAllFarmProds1870)
            
            # Import Census Tract Shapefile into R as SpatialPolygonsDataFrameFormat (SP Dataframe)
            # dsn is location of folder which contains shapefiles, (.proj, .shp etc.)
            # layer is the filename of the .shp file inside the
            # folder dsn points to. 
            
            county1870 <- sf::st_read(dsn = "raw-data/nhgis0002_shape/nhgis0002_shapefile_tl2008_us_county_1870",
                                      layer = "US_county_1870_conflated")
            
            county1870 <-
                county1870 %>%
                merge(data1870, "GISJOIN")
            
            
            # Set projection of tracts dataset to `projection` required by leaflet
            
            county1870 <- sf::st_transform(county1870, crs="+init=epsg:4326")
            
            # Condense size of data for faster processing
            
            county1870 <- rmapshaper::ms_simplify(county1870)
            
            # Set palette color
            
            pal <- colorNumeric("viridis", NULL)
            
            #  Plot the data
            
            leaflet(county1870) %>%
                addTiles() %>%
                addPolygons(stroke = FALSE, smoothFactor = 0.3, fillOpacity = 1,
                            fillColor = ~pal(valueAllFarmProds1870)) %>%
                addLegend(pal = pal, values = ~valueAllFarmProds1870, opacity = 1.0, title = "1870 Value of All Farm Productions,\nby Dollar")
    })
    
    output$model1 <- render_gt({
        
        # experimental model
        
        model1
        
    })
}



# Run the application 

shinyApp(ui = ui, server = server)

```

