---
title: "scratch-save"
author: "Julia Englebert"
date: "4/25/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# DO NOT MAKE CHANGES BELOW THIS LINE

### Map Code
Libraries and data are not loaded, so it won't actually run in this environment

```{r genericGis}

# DO NOT CHANGE THIS

# might also want to add a filter for state??
# if time permits...

# gis template for any year/variable desired
# only change these two lines!
year <- 1870
myvar <- "Average Farm Value"

datayear <- mwData %>%
  # use get() to use the stored variable
  # idk why, but it doesn't work without this
  # the variable must be converted to a double in the original mwData dataset
  mutate(myvariable = (get(myvar))) %>%
  filter(YEAR == year, myvariable > 0) %>%
  select(GISJOIN, myvariable)

# Import Census Tract Shapefile into R as SpatialPolygonsDataFrameFormat (SP Dataframe)
# dsn is location of folder which contains shapefiles, (.proj, .shp etc.)
# layer is the filename of the .shp file inside the
# folder dsn points to. 

dsnyear <- shapefiles %>% 
  filter(Year == year) %>% 
  pull(Dsn)
layeryear <- shapefiles %>% 
  filter(Year == year) %>% 
  pull(Layer)

countyyear <- sf::st_read(dsn = dsnyear,
                         layer = layeryear)

countyyear <-
  countyyear %>%
  merge(datayear, "GISJOIN")


# Set projection of tracts dataset to `projection` required by leaflet

countyyear <- sf::st_transform(countyyear, crs="+init=epsg:4326")

# Condense size of data for faster processing

countyyear <- rmapshaper::ms_simplify(countyyear)

# Set palette color

pal <- colorNumeric("viridis", NULL)

#  Plot the data

# use shiny to add a title, which will be be equivalent to myvar

leaflet(countyyear) %>%
  addTiles() %>%
  addPolygons(stroke = FALSE, smoothFactor = 0.3, fillOpacity = 1,
              fillColor = ~pal(myvariable)) %>%
  addLegend(pal = pal, values = ~myvariable, opacity = 1.0, title = myvar)

```

# Save This
```{r shiny, eval=FALSE}

# DO NOT CHANGE

# Pasting this here in case my computer explodes

# This is a Shiny web application. You can run the application by clicking
# the 'Run App' button above.
#
# Find out more about building applications with Shiny here:
#
#    http://shiny.rstudio.com/
#

library(shiny)
library(haven)
library(tidyverse)
library(gt)
library(devtools)
library(tibble)
library(foreign)
library(scales)
library(shinythemes)
library(plotly)
library(leaflet)
library(broom)

# packages for mapping
library(leaflet)
library(spdplyr)
library(rmapshaper)
library(sf)

# The real data

data1870a <- read.csv("raw-data/nhgis0002_csv/nhgis0002_ds16_1870_county.csv")
data1870b <- read.csv("raw-data/nhgis0002_csv/nhgis0002_ds17_1870_county.csv")
data1870j <- full_join(data1870a, data1870b, by = c("GISJOIN", "STATE", "COUNTY"))

data1880a <- read.csv("raw-data/nhgis0002_csv/nhgis0002_ds22_1880_county.csv") 
data1880b <- read.csv("raw-data/nhgis0002_csv/nhgis0002_ds23_1880_county.csv")
data1880j <- full_join(data1880a, data1880b, by = c("GISJOIN", "STATE", "COUNTY"))

data1890a <- read.csv("raw-data/nhgis0002_csv/nhgis0002_ds26_1890_county.csv")
data1890b <- read.csv("raw-data/nhgis0002_csv/nhgis0002_ds27_1890_county.csv")
data1890j <- full_join(data1890a, data1890b, by = c("GISJOIN", "STATE", "COUNTY"))

data1800s <- bind_rows(data1870j, data1880j, data1890j)


# I'm not actually using this data anymore
# I just wanted to make sure I could get my plots running smoothly
tbl_1 <- read_por("ICPSR_04254_ag/DS0001/04254-0001-Data.por", col_select = c(NAME, UNFIPS, FML_XX_A, ARE_XX_A, FRM_XX_Q, PRP_XX_V, IMP_XX_V, AFP_XX_V)) %>%
    rename(name = NAME, fips = UNFIPS, land_in_farms = FML_XX_A, total_area = ARE_XX_A, num_farms = FRM_XX_Q, value_farms = PRP_XX_V, value_implements = IMP_XX_V, value_production_betterments_stocks = AFP_XX_V)

tbl_3 <- read_por("ICPSR_04254_ag/DS0003/04254-0003-Data.por", col_select = c(NAME, UNFIPS, FML_XX_A, ARE_XX_A, FRM_XX_Q, PRP_XX_V, IMP_XX_V, AFP_XX_V))%>%
    rename(name = NAME, fips = UNFIPS, land_in_farms = FML_XX_A, total_area = ARE_XX_A, num_farms = FRM_XX_Q, value_farms = PRP_XX_V, value_implements = IMP_XX_V, value_production_betterments_stocks = AFP_XX_V)

tbl_5 <- read_por("ICPSR_04254_ag/DS0005/04254-0005-Data.por", col_select = c(NAME, UNFIPS, FML_XX_A, ARE_XX_A, FRM_XX_Q, PRP_OF_V, IMP_XX_V, CRO_XX_V)) %>%
    rename(name = NAME, fips = UNFIPS, land_in_farms = FML_XX_A, total_area = ARE_XX_A, num_farms = FRM_XX_Q, value_implements = IMP_XX_V, value_crops = CRO_XX_V) %>%
    mutate(value_farms = PRP_OF_V) %>%
    mutate(value_livestock = "NA", value_productsNotFed = "NA") %>%
    select(name, fips, land_in_farms, total_area, num_farms, value_farms, value_implements, value_livestock, value_productsNotFed)

tbl_1_d <- read_por("ICPSR_04296_demog/DS0001/04296-0001-Data.por", col_select = c(NAME, UNFIPS, TTOT, FT0_4, FT5_9, FT10_14, FT15_19, FT20_24, FT25_29, MT0_4, MT5_9, MT10_14, MT15_19, MT20_24, MT25_29, POP10P, SCH)) %>%
    rename(name = NAME, fips = UNFIPS, total = TTOT, people_over_10 = POP10P, pupils_in_school = SCH) %>%
    mutate(fem_5_24 = FT5_9 + FT10_14 + FT15_19 + FT20_24, mal_5_24 = MT5_9 + MT10_14 + MT15_19 + MT20_24)

tbl_3_d <- read_por("ICPSR_04296_demog/DS0003/04296-0003-Data.por", col_select = c(NAME, UNFIPS, TTOT, FT0_4, FT5_9, FT10_14, FT15_19, FT20_24, FT25_29, MT0_4, MT5_9, MT10_14, MT15_19, MT20_24, MT25_29, SCH)) %>%
    rename(name = NAME, fips = UNFIPS, total = TTOT, pupils_in_school = SCH) %>%
    mutate(fem_5_24 = FT5_9 + FT10_14 + FT15_19 + FT20_24, mal_5_24 = MT5_9 + MT10_14 + MT15_19 + MT20_24)

tbl_5_d <- read_por("ICPSR_04296_demog/DS0005/04296-0005-Data.por", col_select = c(NAME, UNFIPS, TTOT, FT0_4, FT5_9, FT10_14, FT15_19, FT20_24, FT25_29, MT0_4, MT5_9, MT10_14, MT15_19, MT20_24, MT25_29, SCH69, SCH1014, SCH1517, SCH1820)) %>% 
    rename(name = NAME, fips = UNFIPS, total = TTOT) %>%
    mutate(fem_5_24 = FT5_9 + FT10_14 + FT15_19 + FT20_24, mal_5_24 = MT5_9 + MT10_14 + MT15_19 + MT20_24,
           # Inconsistent age ranges
           # Not sure how to fix this
           pupils_in_school_6_20 = SCH69 + SCH1014 + SCH1517 + SCH1820)

j_1870 <- full_join(tbl_1, tbl_1_d, by = "fips") %>% 
    mutate(perc_school = pupils_in_school/(fem_5_24 + mal_5_24)*100) %>%
    select(name.x, fips, value_farms, perc_school) %>%
    group_by(fips)

j_1870 <- na.omit(j_1870)

j_1890 <- full_join(tbl_3, tbl_3_d, by = "fips") %>%
    mutate(perc_school = pupils_in_school/(fem_5_24 + mal_5_24)*100) %>%
    select(name.x, fips, value_farms, perc_school) %>%
    group_by(fips)

j_1890 <- na.omit(j_1890)


j_1910 <- full_join(tbl_5, tbl_5_d, by = "fips") %>%
    mutate(perc_school = pupils_in_school_6_20/(fem_5_24 + mal_5_24)*100) %>%
    select(name.x, fips, value_farms, perc_school) %>%
    group_by(fips)

j_1910 <- na.omit(j_1910)


b_1870_1910 <- bind_rows("1870" = j_1870, "1890" = j_1890, "1910" = j_1910, .id = "year") %>%
    group_by(year) 

# this should be done by state, not fips!!!
model1 <- lm(data = b_1870_1910, perc_school ~ fips + value_farms) %>% 
    tidy(conf.int = TRUE) %>% 
    gt() %>%
    fmt_number(data = ., columns = c("estimate", "std.error", "statistic", "p.value", "conf.low", "conf.high"), decimals = 2)

# Input

ui <- fluidPage(
    
    # flatly is a nice theme to make the tabs look put together
    
    # Application title
    
    navbarPage("Agriculture and Education in the U.S.", theme = shinytheme("flatly"),
               
               # remember that tab panel is for what shows up in the tab, and title panel is 
               # for what shows up at the top of the page within the tab                  
               
               tabPanel("Tab 1",
                        
                        # Give the page a title
                        titlePanel("Relationship Between Farm Value and Education, by County"),
                        
                        # Generate a row with a sidebar
                        sidebarLayout(      
                            
                            # Define the sidebar with one input
                            # insteaad of region, I want year ######
                            sidebarPanel(
                                selectInput("year", "Year:", 
                                            choices=c("1870" = "1870", "1890" = "1890", "1910" = "1910"), 
                                            multiple = TRUE)),
                            helpText("From Great Plains Population and Environment Survey Agricultural and Social & Demographic Data.")
                        ),
                        
                        # Create a spot for the plot
                        mainPanel(
                            tabsetPanel(id = "tabsMain",
                                        tabPanel("Plot",
                                                 
                                                 # this tells the UI what plot to put 
                                                 
                                                 plotOutput("agPlot")  
                                        )))),
               tabPanel("Models",
                        
                        # Give the page a title
                        titlePanel("Relationship Between Farm Value and Education, by County"),
                        p("Make some models! (See notes)"),
                        gt_output("model1")
               ),
               tabPanel("Maps",
                
                # Give the page a title
                titlePanel("Title Relating to Maps"),
                p("Add a slider for different years/variables & figure out how to get two maps side by side"),
                p("Maps may take up to 30 seconds to load."),
               leafletOutput("map1"),
               p()),
               
               tabPanel("About",
                        
                        # Give the page a title
                        titlePanel("About this project"),
                        p("My name is Julia Englebert. I am a senior at Harvard College studying Near Eastern Languages and Civilizations with a secondary field in Ethnicity, Migration, and Rights. Some of my academic interests include the history and future of Midwestern agriculture, and the role of data science in shaping social policy."),
                        br(),
                        p("This project uses historical census and American Community Survey (ACS) data to explore correlations between agriculture and education in the Midwestern United States. By joining the two datasets, the former containing agricultural data and the later containing demographic data, I was able to look at the impact of farming, land value, crop value, and more on education in Midwestern communities over the course of a century. 
                        I chose this particular time range in part because of the data that was available to me, and in part due to the economic, industrial, and education policy changes that ocurred from 1870 to 1960. 
                          My data is sourced from the IPUMS National Historical Geographic Information System (NHGIS) at nhgis.org. IPUMS provides census data from around the world, but my project focuses specifically on the United States from 1870 to 1960. All datasets and gis files used for this project can be downloaded from the NHGIS Data Finder:"),
                        p(a(href="https://data2.nhgis.org/main", "NHGIS Data Finder")),
                        br(),
                        p("To see more of my work, please visit my Github account:"),
                        p(a(href="https://github.com/julia-englebert", "Julia Englebert")),
                        br(),
                        titlePanel("Citations"),
                        p("Steven Manson, Jonathan Schroeder, David Van Riper, and Steven Ruggles. IPUMS National Historical Geographic Information System: Version 14.0 [Database]. Minneapolis, MN: IPUMS. 2019. http://doi.org/10.18128/D050.V14.0"),
                        p("The College of William and Mary and the Minnesota Population Center. School Attendance Boundary Information System (SABINS): Version 1.0. Minneapolis, MN: University of Minnesota 2011.")
               )
    ))



# use plotly to allow hover text to appear on plots, giving more info about the point

server <- function(input, output) {
    
    # Fill in the spot we created for a plot
    output$agPlot <- renderPlot({
        
        # Render a plot
        b_1870_1910 %>% 
            filter(year %in% input$year) %>% 
            group_by(year) %>%
            ggplot(aes(x = value_farms, y = perc_school, color = year)) + 
            geom_point(alpha = 0.5) + 
            ylim(0, 100) + 
            geom_smooth(method = "lm") + 
            labs(title = "Relationship Between Farm Value and Education, by County", 
                 subtitle = "Great Plains Region, United States", 
                 x = "Total Dollar Value of Farms", 
                 y = "Percent Students Ages 5-24 Enrolled in School") +
            scale_x_log10(labels = comma) +
            theme_classic()
    })
    
    output$map1 <- renderLeaflet({
            data1870 <- data1870j %>%
                filter(STATE == "North Dakota" | STATE == "South Dakota" | STATE == "Nebraska" | STATE == "Minnesota" | STATE == "Iowa" | STATE == "Missouri" | STATE == "Wisconsin" | STATE == "Illinois" | STATE == "Kansas" | STATE == "Michigan" | STATE == "Indiana" | STATE == "Ohio", AJX001 > 0) %>%
                mutate(valueAllFarmProds1870 = AJX001) %>%
                select(GISJOIN, valueAllFarmProds1870)
            
            # Import Census Tract Shapefile into R as SpatialPolygonsDataFrameFormat (SP Dataframe)
            # dsn is location of folder which contains shapefiles, (.proj, .shp etc.)
            # layer is the filename of the .shp file inside the
            # folder dsn points to. 
            
            county1870 <- sf::st_read(dsn = "raw-data/nhgis0002_shape/nhgis0002_shapefile_tl2008_us_county_1870",
                                      layer = "US_county_1870_conflated")
            
            county1870 <-
                county1870 %>%
                merge(data1870, "GISJOIN")
            
            
            # Set projection of tracts dataset to `projection` required by leaflet
            
            county1870 <- sf::st_transform(county1870, crs="+init=epsg:4326")
            
            # Condense size of data for faster processing
            
            county1870 <- rmapshaper::ms_simplify(county1870)
            
            # Set palette color
            
            pal <- colorNumeric("viridis", NULL)
            
            #  Plot the data
            
            leaflet(county1870) %>%
                addTiles() %>%
                addPolygons(stroke = FALSE, smoothFactor = 0.3, fillOpacity = 1,
                            fillColor = ~pal(valueAllFarmProds1870)) %>%
                addLegend(pal = pal, values = ~valueAllFarmProds1870, opacity = 1.0, title = "1870 Value of All Farm Productions,\nby Dollar")
    })
    
    output$model1 <- render_gt({
        
        # experimental model
        
        model1
        
    })
}



# Run the application 

shinyApp(ui = ui, server = server)

```